name: Build and Release

on:
  push:
    branches:
      - master  # 監視するブランチを指定。必要に応じて変更してください。

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: '2022.3.32f1'

      - name: Build project
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: StandaloneWindows64

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/update_0.2.0.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}